/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanltthuvien.View;

import java.lang.reflect.Array;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mycompany.quanltthuvien.Controller.AdminController;
import com.mycompany.quanltthuvien.Model.Sach;
import com.mycompany.quanltthuvien.Model.TaiKhoan;
import com.mycompany.quanltthuvien.Model.TheLoai;

/**
 *
 * @author Legion
 */
public class Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form Admin
     */
    AdminController adminController = new AdminController();
    public Admin() {
        initComponents();
        setSize(1024, 768); // hoặc kích thước bạn muốn
        setLocationRelativeTo(null);
        LoadSachTable(adminController.GetAllSach());
        LoadSachTheLoai(adminController.GetGetAllTheLoai());
        LoadTheLoaiTable(adminController.GetGetAllTheLoai());
    }

    private void LoadSachTable(ArrayList<Sach> listSach) {
        DefaultTableModel model = (DefaultTableModel) Sach_tbSach.getModel();
        model.setRowCount(0);
        for(int i = 0; i < listSach.size(); i++){
            model.addRow(new Object[]{
                listSach.get(i).getMaSach(),
                listSach.get(i).getTenSach(),
                listSach.get(i).getSoLuong(),
                listSach.get(i).getTacGia(),
                adminController.GetTheLoaiByMa(listSach.get(i).getMaTheLoai()).getTenTheLoai()
            });
        }
    }

    private void LoadSachTheLoai(ArrayList<TheLoai> listSach){
        DefaultTableModel model = (DefaultTableModel) Sach_tbTheLoai.getModel();
        model.setRowCount(0);
        for(int i = 0; i < listSach.size(); i++){
            model.addRow(new Object[]{
                listSach.get(i).getTenTheLoai()
            });
        }
    }
    private void LoadTheLoaiTable(ArrayList<TheLoai> listTheLoai) {
        DefaultTableModel model = (DefaultTableModel) TheLoai_tbTheLoai.getModel();
        model.setRowCount(0);
        for(int i = 0; i < listTheLoai.size(); i++){
            model.addRow(new Object[]{
                listTheLoai.get(i).getMaTheLoai(),
                listTheLoai.get(i).getTenTheLoai()
            });
        }
    }

    private String vaitro(String role){
        if(role.equals("AD")){
            return "Admin";
        }else if(role.equals("MG")) {
            return "Mangager";
        }
        return "EROR";
    }

    private void LoadTaiKhoan(ArrayList<TaiKhoan> listTaiKhoan){
        DefaultTableModel model = (DefaultTableModel) TaiKhoan_tbTaiKhoan.getModel();
        model.setRowCount(0);
        for(int i = 0; i < listTaiKhoan.size(); i++){
            model.addRow(new Object[]{
                listTaiKhoan.get(i).getUsername(),
                listTaiKhoan.get(i).getPass(),
                listTaiKhoan.get(i).getSdtTK(),
                vaitro(listTaiKhoan.get(i).getRole())
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminCT = new javax.swing.JTabbedPane();
        Sach = new javax.swing.JPanel();
        Sach_lbTenSach = new javax.swing.JLabel();
        Sach_lbSoLuong = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Sach_txtTenSach = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Sach_txtSoLuong = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Sach_tbSach = new javax.swing.JTable();
        Sach_lbTheLoai = new javax.swing.JLabel();
        Sach_butThem = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Sach_txtTheLoai = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        Sach_tfTimKiem = new javax.swing.JTextPane();
        Sach_butXoa = new javax.swing.JButton();
        Sach_butTimKiem = new javax.swing.JButton();
        Sach_butLamMoi = new javax.swing.JButton();
        Sach_butSua = new javax.swing.JButton();
        Sach_butHienThi = new javax.swing.JButton();
        Sach_cbTimTheo = new javax.swing.JComboBox<>();
        jScrollPane17 = new javax.swing.JScrollPane();
        Sach_txtTacGia = new javax.swing.JTextPane();
        Sach_lbTenSach1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Sach_tbTheLoai = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Sach_TxtTenTheloai = new javax.swing.JTextField();
        TheLoai = new javax.swing.JPanel();
        TheLoai_butThem = new javax.swing.JButton();
        TheLoai_butSua = new javax.swing.JButton();
        TheLoai_butXoa = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TheLoai_txtTheLoai = new javax.swing.JTextPane();
        TheLoai_lbTheLoai = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TheLoai_tfTimKiem = new javax.swing.JTextPane();
        TheLoai_butTimKiem = new javax.swing.JButton();
        TheLoai_butHienThi = new javax.swing.JButton();
        TheLoai_cbTimTheo = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        TheLoai_tbTheLoai = new javax.swing.JTable();
        TaiKhoan = new javax.swing.JPanel();
        TaiKhoan_lbTenTaiKhoan = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TaiKhoan_txtTenTaiKhoan = new javax.swing.JTextPane();
        TaiKhoan__butThem = new javax.swing.JButton();
        TaiKhoan__butSua = new javax.swing.JButton();
        TaiKhoan__butXoa = new javax.swing.JButton();
        TaiKhoan_lbMatKhau = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TaiKhoan_txtMatKhau = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        Sach_tfTimKiem1 = new javax.swing.JTextPane();
        Sach_butTimKiem1 = new javax.swing.JButton();
        Sach_butHienThi1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        TaiKhoan_tbTaiKhoan = new javax.swing.JTable();
        TaiKhoan_lbTimTheoTenTK = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        TaiKhoan_txtTenTK = new javax.swing.JTextPane();
        TaiKhoan_lbMatKhau1 = new javax.swing.JLabel();
        TaiKhoan_lbMatKhau2 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        TaiKhoan_txtSDT = new javax.swing.JTextPane();
        LichSuGiaoDich = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        TruyVan_Lsu = new javax.swing.JTable();
        TruyVan_bt = new javax.swing.JButton();
        TruyVan_txtNamMuon = new javax.swing.JTextField();
        TruyVan_txtNgayMuon = new javax.swing.JTextField();
        TruyVan_txtThangMuon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        TruyVan_txtNgayTra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TruyVan_txtThangTra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TruyVan_txtNamTra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TruyVan_btLayThongTin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        info_TenTK = new javax.swing.JTextField();
        info_SDT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        Sach.setDoubleBuffered(false);
        Sach.setLayout(null);

        Sach_lbTenSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sach_lbTenSach.setText("Tên Sách:");
        Sach.add(Sach_lbTenSach);
        Sach_lbTenSach.setBounds(30, 22, 75, 22);

        Sach_lbSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sach_lbSoLuong.setText("Số lượng:");
        Sach.add(Sach_lbSoLuong);
        Sach_lbSoLuong.setBounds(30, 62, 75, 22);

        jScrollPane1.setViewportView(Sach_txtTenSach);

        Sach.add(jScrollPane1);
        jScrollPane1.setBounds(111, 22, 160, 22);

        jScrollPane2.setViewportView(Sach_txtSoLuong);

        Sach.add(jScrollPane2);
        jScrollPane2.setBounds(111, 62, 160, 22);

        Sach_tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Số lượng", "Tác giả", "Thể loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Sach_tbSach);

        Sach.add(jScrollPane3);
        jScrollPane3.setBounds(30, 228, 753, 440);

        Sach_lbTheLoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sach_lbTheLoai.setText("Thể loại:");
        Sach.add(Sach_lbTheLoai);
        Sach_lbTheLoai.setBounds(30, 102, 75, 22);

        Sach_butThem.setLabel("Thêm");
        Sach_butThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sach_butThemActionPerformed(evt);
            }
        });
        Sach.add(Sach_butThem);
        Sach_butThem.setBounds(335, 21, 72, 23);

        jScrollPane5.setViewportView(Sach_txtTheLoai);

        Sach.add(jScrollPane5);
        jScrollPane5.setBounds(111, 102, 160, 22);

        jScrollPane6.setViewportView(Sach_tfTimKiem);

        Sach.add(jScrollPane6);
        jScrollPane6.setBounds(166, 179, 285, 22);

        Sach_butXoa.setText("Xóa");
        Sach_butXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sach_butXoaActionPerformed(evt);
            }
        });
        Sach.add(Sach_butXoa);
        Sach_butXoa.setBounds(515, 21, 72, 23);

        Sach_butTimKiem.setText("Tìm kiếm");
        Sach_butTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sach_butTimKiemActionPerformed(evt);
            }
        });
        Sach.add(Sach_butTimKiem);
        Sach_butTimKiem.setBounds(469, 179, 79, 23);

        Sach_butLamMoi.setText("Làm mới");
        Sach_butLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sach_butLamMoiActionPerformed(evt);
            }
        });
        Sach.add(Sach_butLamMoi);
        Sach_butLamMoi.setBounds(1325, 686, 142, 32);

        Sach_butSua.setText("Sửa");
        Sach_butSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sach_butSuaActionPerformed(evt);
            }
        });
        Sach.add(Sach_butSua);
        Sach_butSua.setBounds(425, 21, 72, 23);

        Sach_butHienThi.setText("Hiển thị");
        Sach.add(Sach_butHienThi);
        Sach_butHienThi.setBounds(1247, 179, 72, 23);

        Sach_cbTimTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tim theo tên", "Tim theo mã", "Tim theo thể loại" }));
        Sach.add(Sach_cbTimTheo);
        Sach_cbTimTheo.setBounds(30, 179, 124, 22);

        jScrollPane17.setViewportView(Sach_txtTacGia);

        Sach.add(jScrollPane17);
        jScrollPane17.setBounds(111, 136, 160, 22);

        Sach_lbTenSach1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sach_lbTenSach1.setText("Tác giả:");
        Sach.add(Sach_lbTenSach1);
        Sach_lbTenSach1.setBounds(30, 136, 75, 22);

        Sach_tbTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tên thể loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(Sach_tbTheLoai);

        Sach.add(jScrollPane4);
        jScrollPane4.setBounds(820, 180, 170, 402);

        jLabel8.setText("Danh sách thể loại");
        Sach.add(jLabel8);
        jLabel8.setBounds(830, 160, 140, 16);

        jButton2.setText("Lấy thể loại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Sach.add(jButton2);
        jButton2.setBounds(850, 130, 110, 23);

        Sach_TxtTenTheloai.setText("Nhập tên thể loại");
        Sach_TxtTenTheloai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sach_TxtTenTheloaiMouseClicked(evt);
            }
        });
        Sach.add(Sach_TxtTenTheloai);
        Sach_TxtTenTheloai.setBounds(800, 80, 190, 22);

        AdminCT.addTab("Sách", Sach);
        Sach.getAccessibleContext().setAccessibleName("");

        TheLoai.setDoubleBuffered(false);

        TheLoai_butThem.setLabel("Thêm");
        TheLoai_butThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheLoai_butThemActionPerformed(evt);
            }
        });

        TheLoai_butSua.setText("Sửa");
        TheLoai_butSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheLoai_butSuaActionPerformed(evt);
            }
        });

        TheLoai_butXoa.setText("Xóa");
        TheLoai_butXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheLoai_butXoaActionPerformed(evt);
            }
        });

        jScrollPane9.setViewportView(TheLoai_txtTheLoai);

        TheLoai_lbTheLoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TheLoai_lbTheLoai.setText("Thể loại:");

        jScrollPane10.setViewportView(TheLoai_tfTimKiem);

        TheLoai_butTimKiem.setText("Tìm kiếm");
        TheLoai_butTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheLoai_butTimKiemActionPerformed(evt);
            }
        });

        TheLoai_butHienThi.setText("Hiển thị");
        TheLoai_butHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheLoai_butHienThiActionPerformed(evt);
            }
        });

        TheLoai_cbTimTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm theo mã", "Tìm theo tên" }));

        TheLoai_tbTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã thể loại", "Tên thể loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(TheLoai_tbTheLoai);

        javax.swing.GroupLayout TheLoaiLayout = new javax.swing.GroupLayout(TheLoai);
        TheLoai.setLayout(TheLoaiLayout);
        TheLoaiLayout.setHorizontalGroup(
            TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TheLoaiLayout.createSequentialGroup()
                .addGroup(TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TheLoaiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TheLoaiLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(TheLoaiLayout.createSequentialGroup()
                                .addComponent(TheLoai_lbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TheLoai_butThem))
                            .addGroup(TheLoaiLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TheLoai_cbTimTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10)))
                        .addGap(18, 18, 18)
                        .addGroup(TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TheLoai_butSua)
                            .addComponent(TheLoai_butTimKiem))
                        .addGap(18, 18, 18)
                        .addGroup(TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TheLoai_butXoa)
                            .addComponent(TheLoai_butHienThi))))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        TheLoaiLayout.setVerticalGroup(
            TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TheLoaiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TheLoai_butThem)
                        .addComponent(TheLoai_butXoa)
                        .addComponent(TheLoai_butSua))
                    .addComponent(TheLoai_lbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TheLoai_butTimKiem)
                        .addComponent(TheLoai_butHienThi))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TheLoai_cbTimTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        AdminCT.addTab("Thể loại", TheLoai);

        TaiKhoan.setDoubleBuffered(false);

        TaiKhoan_lbTenTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaiKhoan_lbTenTaiKhoan.setText("Tên tài khoản:");

        jScrollPane11.setViewportView(TaiKhoan_txtTenTaiKhoan);

        TaiKhoan__butThem.setLabel("Thêm");
        TaiKhoan__butThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaiKhoan__butThemActionPerformed(evt);
            }
        });

        TaiKhoan__butSua.setText("Sửa");
        TaiKhoan__butSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaiKhoan__butSuaActionPerformed(evt);
            }
        });

        TaiKhoan__butXoa.setText("Xóa");
        TaiKhoan__butXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaiKhoan__butXoaActionPerformed(evt);
            }
        });

        TaiKhoan_lbMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaiKhoan_lbMatKhau.setText("Mật khẩu:");

        jScrollPane12.setViewportView(TaiKhoan_txtMatKhau);

        jScrollPane13.setViewportView(Sach_tfTimKiem1);

        Sach_butTimKiem1.setText("Tìm kiếm");
        Sach_butTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sach_butTimKiem1ActionPerformed(evt);
            }
        });

        Sach_butHienThi1.setText("Hiển thị");
        Sach_butHienThi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sach_butHienThi1ActionPerformed(evt);
            }
        });

        TaiKhoan_tbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Mật khẩu", "Số điện thoại", "Vai trò"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(TaiKhoan_tbTaiKhoan);

        TaiKhoan_lbTimTheoTenTK.setText("Tìm theo tên tài khoản");

        jScrollPane15.setViewportView(TaiKhoan_txtTenTK);

        TaiKhoan_lbMatKhau1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaiKhoan_lbMatKhau1.setText("Tên:");

        TaiKhoan_lbMatKhau2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaiKhoan_lbMatKhau2.setText("Số điện thoại");

        jScrollPane16.setViewportView(TaiKhoan_txtSDT);

        javax.swing.GroupLayout TaiKhoanLayout = new javax.swing.GroupLayout(TaiKhoan);
        TaiKhoan.setLayout(TaiKhoanLayout);
        TaiKhoanLayout.setHorizontalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                        .addComponent(TaiKhoan_lbMatKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                        .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TaiKhoanLayout.createSequentialGroup()
                                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                                        .addComponent(TaiKhoan_lbTimTheoTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane13))
                                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                                        .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TaiKhoan_lbTenTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(TaiKhoan_lbMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TaiKhoan_lbMatKhau1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                            .addComponent(jScrollPane12)
                                            .addComponent(jScrollPane15)
                                            .addComponent(jScrollPane16))))
                                .addGap(18, 18, 18)
                                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                                        .addComponent(TaiKhoan__butThem)
                                        .addGap(18, 18, 18)
                                        .addComponent(TaiKhoan__butSua)
                                        .addGap(18, 18, 18)
                                        .addComponent(TaiKhoan__butXoa))
                                    .addComponent(Sach_butTimKiem1))
                                .addGap(133, 133, 133)
                                .addComponent(Sach_butHienThi1))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))))
        );
        TaiKhoanLayout.setVerticalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane11)
                        .addComponent(TaiKhoan_lbTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TaiKhoan__butThem)
                        .addComponent(TaiKhoan__butXoa)
                        .addComponent(TaiKhoan__butSua)))
                .addGap(18, 18, 18)
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane12)
                    .addComponent(TaiKhoan_lbMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaiKhoan_lbMatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TaiKhoan_lbMatKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaiKhoanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sach_butHienThi1)
                .addGap(1, 1, 1)
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sach_butTimKiem1)
                    .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TaiKhoan_lbTimTheoTenTK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        AdminCT.addTab("Quản lý tài khoản", TaiKhoan);

        LichSuGiaoDich.setDoubleBuffered(false);

        TruyVan_Lsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã giao dịch", "Tên tài khoản", "Mã khách hàng", "Ngày giao dịch", "Số lượng", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane14.setViewportView(TruyVan_Lsu);

        TruyVan_bt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TruyVan_bt.setText("Truy vấn");
        TruyVan_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_btActionPerformed(evt);
            }
        });

        TruyVan_txtNamMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtNamMuonActionPerformed(evt);
            }
        });

        TruyVan_txtNgayMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtNgayMuonActionPerformed(evt);
            }
        });

        TruyVan_txtThangMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtThangMuonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("/");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("/");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("/");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("/");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        TruyVan_txtNgayTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtNgayTraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("/");

        TruyVan_txtThangTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtThangTraActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setText("/");

        TruyVan_txtNamTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtNamTraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("đến");

        TruyVan_btLayThongTin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TruyVan_btLayThongTin.setText("Lấy thông tin");

        javax.swing.GroupLayout LichSuGiaoDichLayout = new javax.swing.GroupLayout(LichSuGiaoDich);
        LichSuGiaoDich.setLayout(LichSuGiaoDichLayout);
        LichSuGiaoDichLayout.setHorizontalGroup(
            LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TruyVan_txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                                .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TruyVan_txtThangMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(6, 6, 6)
                                .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TruyVan_txtNamMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TruyVan_btLayThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(TruyVan_txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(TruyVan_txtThangTra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(TruyVan_txtNamTra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TruyVan_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        LichSuGiaoDichLayout.setVerticalGroup(
            LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(TruyVan_txtThangTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(TruyVan_txtNamTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TruyVan_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(TruyVan_btLayThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(LichSuGiaoDichLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(LichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TruyVan_txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TruyVan_txtThangMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TruyVan_txtNamMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TruyVan_txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        AdminCT.addTab("Truy Vấn", LichSuGiaoDich);
        LichSuGiaoDich.getAccessibleContext().setAccessibleName("");

        jPanel1.setLayout(null);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Đăng Xuất");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(740, 440, 142, 39);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Tên tài khoản:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 160, 222, 48);

        info_TenTK.setEditable(false);
        info_TenTK.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        info_TenTK.setText("jTextField1");
        jPanel1.add(info_TenTK);
        info_TenTK.setBounds(310, 160, 600, 54);

        info_SDT.setEditable(false);
        info_SDT.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        info_SDT.setText("jTextField1");
        jPanel1.add(info_SDT);
        info_SDT.setBounds(310, 270, 600, 54);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Số điện thoại:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 270, 217, 48);

        AdminCT.addTab("Thông tin tài khoản", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminCT)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminCT)
        );

        AdminCT.getAccessibleContext().setAccessibleName("Admin");
        AdminCT.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sach_butThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sach_butThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sach_butThemActionPerformed

    private void Sach_butXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sach_butXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sach_butXoaActionPerformed

    private boolean SachIsEmty(){
        if(Sach_txtTenSach.getText().equals("") || Sach_txtSoLuong.getText().equals("") || Sach_txtTheLoai.getText().equals("") || Sach_txtTacGia.getText().equals("")){
            return true;
        }
        return false;
    }
    private void Sach_butTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sach_butTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sach_butTimKiemActionPerformed

    private void Sach_butLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sach_butLamMoiActionPerformed
        // TODO add your handling code here:
        if(SachIsEmty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sách!");
        } else {
            Sach_txtTenSach.setText("");
            Sach_txtSoLuong.setText("");
            Sach_txtTheLoai.setText("");
            Sach_txtTacGia.setText("");
        }
        String tenSach = Sach_txtTenSach.getText();
        String theLoai = Sach_txtTheLoai.getText();
        String tacGia = Sach_txtTacGia.getText();
        ArrayList<Sach> listSach = adminController.GetSachByTenSach(tenSach);
        for(int i = 0; i < listSach.size(); i++){
            if()
        }
    }//GEN-LAST:event_Sach_butLamMoiActionPerformed

    private void Sach_butSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sach_butSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sach_butSuaActionPerformed

    private void TheLoai_butThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheLoai_butThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheLoai_butThemActionPerformed

    private void TheLoai_butSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheLoai_butSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheLoai_butSuaActionPerformed

    private void TheLoai_butXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheLoai_butXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheLoai_butXoaActionPerformed

    private void TheLoai_butTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheLoai_butTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheLoai_butTimKiemActionPerformed

    private void TaiKhoan__butThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaiKhoan__butThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaiKhoan__butThemActionPerformed

    private void TaiKhoan__butSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaiKhoan__butSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaiKhoan__butSuaActionPerformed

    private void TaiKhoan__butXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaiKhoan__butXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaiKhoan__butXoaActionPerformed

    private void Sach_butTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sach_butTimKiem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sach_butTimKiem1ActionPerformed

    private void Sach_butHienThi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sach_butHienThi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sach_butHienThi1ActionPerformed

    private void TruyVan_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_btActionPerformed

    private void TruyVan_txtNamMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtNamMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtNamMuonActionPerformed

    private void TruyVan_txtNgayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtNgayMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtNgayMuonActionPerformed

    private void TruyVan_txtThangMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtThangMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtThangMuonActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void TruyVan_txtNgayTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtNgayTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtNgayTraActionPerformed

    private void TruyVan_txtThangTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtThangTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtThangTraActionPerformed

    private void TruyVan_txtNamTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtNamTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtNamTraActionPerformed

    private void Logout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Sach_TxtTenTheloaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sach_TxtTenTheloaiMouseClicked
        // TODO add your handling code here:
        Sach_txtTheLoai.setText("");
    }//GEN-LAST:event_Sach_TxtTenTheloaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminCT;
    private javax.swing.JPanel LichSuGiaoDich;
    private javax.swing.JPanel Sach;
    private javax.swing.JTextField Sach_TxtTenTheloai;
    private javax.swing.JButton Sach_butHienThi;
    private javax.swing.JButton Sach_butHienThi1;
    private javax.swing.JButton Sach_butLamMoi;
    private javax.swing.JButton Sach_butSua;
    private javax.swing.JButton Sach_butThem;
    private javax.swing.JButton Sach_butTimKiem;
    private javax.swing.JButton Sach_butTimKiem1;
    private javax.swing.JButton Sach_butXoa;
    private javax.swing.JComboBox<String> Sach_cbTimTheo;
    private javax.swing.JLabel Sach_lbSoLuong;
    private javax.swing.JLabel Sach_lbTenSach;
    private javax.swing.JLabel Sach_lbTenSach1;
    private javax.swing.JLabel Sach_lbTheLoai;
    private javax.swing.JTable Sach_tbSach;
    private javax.swing.JTable Sach_tbTheLoai;
    private javax.swing.JTextPane Sach_tfTimKiem;
    private javax.swing.JTextPane Sach_tfTimKiem1;
    private javax.swing.JTextPane Sach_txtSoLuong;
    private javax.swing.JTextPane Sach_txtTacGia;
    private javax.swing.JTextPane Sach_txtTenSach;
    private javax.swing.JTextPane Sach_txtTheLoai;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JButton TaiKhoan__butSua;
    private javax.swing.JButton TaiKhoan__butThem;
    private javax.swing.JButton TaiKhoan__butXoa;
    private javax.swing.JLabel TaiKhoan_lbMatKhau;
    private javax.swing.JLabel TaiKhoan_lbMatKhau1;
    private javax.swing.JLabel TaiKhoan_lbMatKhau2;
    private javax.swing.JLabel TaiKhoan_lbTenTaiKhoan;
    private javax.swing.JLabel TaiKhoan_lbTimTheoTenTK;
    private javax.swing.JTable TaiKhoan_tbTaiKhoan;
    private javax.swing.JTextPane TaiKhoan_txtMatKhau;
    private javax.swing.JTextPane TaiKhoan_txtSDT;
    private javax.swing.JTextPane TaiKhoan_txtTenTK;
    private javax.swing.JTextPane TaiKhoan_txtTenTaiKhoan;
    private javax.swing.JPanel TheLoai;
    private javax.swing.JButton TheLoai_butHienThi;
    private javax.swing.JButton TheLoai_butSua;
    private javax.swing.JButton TheLoai_butThem;
    private javax.swing.JButton TheLoai_butTimKiem;
    private javax.swing.JButton TheLoai_butXoa;
    private javax.swing.JComboBox<String> TheLoai_cbTimTheo;
    private javax.swing.JLabel TheLoai_lbTheLoai;
    private javax.swing.JTable TheLoai_tbTheLoai;
    private javax.swing.JTextPane TheLoai_tfTimKiem;
    private javax.swing.JTextPane TheLoai_txtTheLoai;
    private javax.swing.JTable TruyVan_Lsu;
    private javax.swing.JButton TruyVan_bt;
    private javax.swing.JButton TruyVan_btLayThongTin;
    private javax.swing.JTextField TruyVan_txtNamMuon;
    private javax.swing.JTextField TruyVan_txtNamTra;
    private javax.swing.JTextField TruyVan_txtNgayMuon;
    private javax.swing.JTextField TruyVan_txtNgayTra;
    private javax.swing.JTextField TruyVan_txtThangMuon;
    private javax.swing.JTextField TruyVan_txtThangTra;
    private javax.swing.JTextField info_SDT;
    private javax.swing.JTextField info_TenTK;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
