/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanltthuvien.View;

import com.mycompany.quanltthuvien.Model.KhachHang;
import com.mycompany.quanltthuvien.Model.Muon;
import com.mycompany.quanltthuvien.Model.Sach;
import com.mycompany.quanltthuvien.Controller.ManagerController;
import com.mycompany.quanltthuvien.Service.SachService;
import java.io.IOException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author hienb
 */
public class Manager extends javax.swing.JFrame {
    ManagerController managerController = new ManagerController();
    SachService sachService = new SachService();
    
    String usernameLogin = "admin";
    /**
     * Creates new form NewJFrame
     */
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Muon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Muon_tbDSMuon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Muon_tbSach = new javax.swing.JTable();
        Muon_lbSLMuon = new javax.swing.JLabel();
        Muon_txtSLMuon = new javax.swing.JTextField();
        Muon_bt = new javax.swing.JButton();
        Muon_lbMaKH = new javax.swing.JLabel();
        Muon_txtMaKH = new javax.swing.JTextField();
        Muon_lbTenKH1 = new javax.swing.JLabel();
        Muon_txtTenKH1 = new javax.swing.JTextField();
        Muon_txtMaSach = new javax.swing.JTextField();
        Muon_lbMaSach = new javax.swing.JLabel();
        Muon_btTim1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Muon.setLayout(null);

        Muon_tbDSMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã mượn", "Mã sách", "Số lượng mượn", "Ngày mượn"
            }
        ));
        Muon_tbDSMuon.setEnabled(false);
        jScrollPane1.setViewportView(Muon_tbDSMuon);

        Muon.add(jScrollPane1);
        jScrollPane1.setBounds(40, 230, 660, 290);

        Muon_tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Số lượng"
            }
        ));
        Muon_tbSach.setEnabled(false);
        jScrollPane2.setViewportView(Muon_tbSach);

        Muon.add(jScrollPane2);
        jScrollPane2.setBounds(733, 0, 230, 520);

        Muon_lbSLMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbSLMuon.setText("Số lượng mượn:");
        Muon.add(Muon_lbSLMuon);
        Muon_lbSLMuon.setBounds(60, 170, 120, 30);

        Muon_txtSLMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtSLMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtSLMuonActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtSLMuon);
        Muon_txtSLMuon.setBounds(180, 170, 221, 26);

        Muon_bt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_bt.setText("Mượn");
        Muon_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_btActionPerformed(evt);
            }
        });
        Muon.add(Muon_bt);
        Muon_bt.setBounds(430, 130, 90, 27);

        Muon_lbMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbMaKH.setText("Mã khách hàng:");
        Muon.add(Muon_lbMaKH);
        Muon_lbMaKH.setBounds(60, 50, 120, 30);

        Muon_txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtMaKHActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtMaKH);
        Muon_txtMaKH.setBounds(180, 50, 221, 26);

        Muon_lbTenKH1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbTenKH1.setText("Tên khách hàng: ");
        Muon.add(Muon_lbTenKH1);
        Muon_lbTenKH1.setBounds(60, 90, 120, 30);

        Muon_txtTenKH1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtTenKH1.setEnabled(false);
        Muon_txtTenKH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtTenKH1ActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtTenKH1);
        Muon_txtTenKH1.setBounds(180, 90, 221, 26);

        Muon_txtMaSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtMaSachActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtMaSach);
        Muon_txtMaSach.setBounds(180, 130, 221, 26);

        Muon_lbMaSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbMaSach.setText("Mã sách:");
        Muon.add(Muon_lbMaSach);
        Muon_lbMaSach.setBounds(60, 130, 120, 30);

        Muon_btTim1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_btTim1.setText("Tìm kiếm");
        Muon_btTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_btTim1ActionPerformed(evt);
            }
        });
        Muon.add(Muon_btTim1);
        Muon_btTim1.setBounds(430, 50, 90, 27);

        jTabbedPane1.addTab("Mượn sách", Muon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Muon_txtSLMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtSLMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtSLMuonActionPerformed

    private void Muon_txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtMaKHActionPerformed

    private void Muon_txtTenKH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtTenKH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtTenKH1ActionPerformed

    private void Muon_txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtMaSachActionPerformed

    private void Muon_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_btActionPerformed
        try {                                        
            // TODO add your handling code here:
            if(Muon_txtTenKH1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng tìm khách hàng trước!");
                return;
            }
            
            String maKH = Muon_txtMaKH.getText().trim();
            String maSach = Muon_txtMaSach.getText().trim();
            String slMuon = Muon_txtSLMuon.getText().trim();
            
            if(maSach.isEmpty() || slMuon.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách và số lượng!");
                return;
            }
            
            int soluongMuon = 0;
            try {
                soluongMuon = Integer.parseInt(slMuon);
                if(soluongMuon <= 0) throw new Exception();
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Số lượng mượn không hợp lệ!");
                return;
            }
            
            // Kiểm tra sách tồn tại
            Sach sach = sachService.GetSachByMa(maSach);
            if(sach == null) {
                JOptionPane.showMessageDialog(this, "Sách này không tồn tại!");
                return;
            }
            
            // Tạo đối tượng Mượn
            Muon muon = new Muon();
            muon.setMaKH(maKH);
            muon.setMaSach(maSach);
            muon.setSoLuong(soluongMuon);
            
            boolean result = managerController.MuonSach(muon, usernameLogin);
            
            if(result) {
                JOptionPane.showMessageDialog(this, "Mượn sách thành công!");
                loadTableSachDaMuon(maKH);
                loadTableKhoSach();
            }
            else {
                JOptionPane.showMessageDialog(this, "Mượn sách thất bại!");
            }
            
        } catch(IOException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null,ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Muon_btActionPerformed

    private void loadTableSachDaMuon(String maKH) {
        DefaultTableModel model = (DefaultTableModel) Muon_tbDSMuon.getModel();
        model.setRowCount(0);
        
        ArrayList<Muon> list = managerController.GetMuonByMa(maKH);
        
        if(list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sách đã mượn!");
            return;
        }
        
        for(Muon m : list) {
            model.addRow(new Object[]
            {
                m.getMaMuon(),
                m.getMaSach(),
                m.getSoLuong(),
                m.getNgayMuon()
            }); 
        }
    }
    
    // Clear dữ liệu Bảng nếu KH không tồn tại
    private void clearTableMuon() {
        DefaultTableModel model = (DefaultTableModel) Muon_tbDSMuon.getModel();
        model.setRowCount(0);
    }
    
    private void loadTableKhoSach()  {
        try {
            DefaultTableModel model = (DefaultTableModel) Muon_tbSach.getModel();
            model.setRowCount(0);
            
            ArrayList<Sach> list = sachService.GetAllSach();
            
            for(Sach s : list) {
                model.addRow(new Object[] {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getSoLuong()
                });
            }
        } catch (IOException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Muon_btTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_btTim1ActionPerformed
        // TODO add your handling code here:
        String maKH = Muon_txtMaKH.getText().trim();
        
        if(maKH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng!");
            return;
        }
        
        KhachHang khachHang = managerController.GetKhachHangByMa(maKH);
        
        if(khachHang == null) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy người dùng này!!!");
            Muon_txtTenKH1.setText("");
            clearTableMuon();
            return;
        }
        // Hiển thị tên khách hàng
        Muon_txtTenKH1.setText(khachHang.getTenKH());
        Muon_txtTenKH1.setEditable(false);
        
        // Load dữ liệu
        loadTableSachDaMuon(maKH);
        loadTableKhoSach();
    }//GEN-LAST:event_Muon_btTim1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Muon;
    private javax.swing.JButton Muon_bt;
    private javax.swing.JButton Muon_btTim1;
    private javax.swing.JLabel Muon_lbMaKH;
    private javax.swing.JLabel Muon_lbMaSach;
    private javax.swing.JLabel Muon_lbSLMuon;
    private javax.swing.JLabel Muon_lbTenKH1;
    private javax.swing.JTable Muon_tbDSMuon;
    private javax.swing.JTable Muon_tbSach;
    private javax.swing.JTextField Muon_txtMaKH;
    private javax.swing.JTextField Muon_txtMaSach;
    private javax.swing.JTextField Muon_txtSLMuon;
    private javax.swing.JTextField Muon_txtTenKH1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
