/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanltthuvien.View;

import com.mycompany.quanltthuvien.Model.KhachHang;
import com.mycompany.quanltthuvien.Model.Muon;
import com.mycompany.quanltthuvien.Model.Sach;
import com.mycompany.quanltthuvien.Controller.ManagerController;
import com.mycompany.quanltthuvien.Service.SachService;
import java.io.IOException;
import java.time.LocalDate;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author hienb
 */
public class Manager extends javax.swing.JFrame {
    ManagerController managerController = new ManagerController();
    SachService sachService = new SachService();
    
    String usernameLogin = "admin";
    /**
     * Creates new form NewJFrame
     */
    public Manager() {
        initComponents();
        setSize(1024, 768); // hoặc kích thước bạn muốn
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TimKiem = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TimKiem_tbDSKH = new javax.swing.JTable();
        TimKiem_cbGet = new javax.swing.JComboBox<>();
        TimKiem_btTim = new javax.swing.JButton();
        TimKiem_btMuon = new javax.swing.JButton();
        TimKiem_lbSDT = new javax.swing.JLabel();
        TimKiem_lbMaKH = new javax.swing.JLabel();
        TimKiem_lbTenKH = new javax.swing.JLabel();
        TimKiem_txtSDT = new javax.swing.JTextField();
        TimKiem_txtMaKH = new javax.swing.JTextField();
        TimKiem_txtTenKH = new javax.swing.JTextField();
        TimKiem_lbTimTheo = new javax.swing.JLabel();
        Muon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Muon_tbDSMuon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Muon_tbSach = new javax.swing.JTable();
        Muon_lbSLMuon = new javax.swing.JLabel();
        Muon_txtSLMuon = new javax.swing.JTextField();
        Muon_bt = new javax.swing.JButton();
        Muon_lbMaKH = new javax.swing.JLabel();
        Muon_txtMaKH = new javax.swing.JTextField();
        Muon_lbTenKH = new javax.swing.JLabel();
        Muon_txtTenKH = new javax.swing.JTextField();
        Muon_txtTenSach = new javax.swing.JTextField();
        Muon_lbTenSach = new javax.swing.JLabel();
        Muon_btTim = new javax.swing.JButton();
        Muon_lbDSMuon = new javax.swing.JLabel();
        Muon_lbTheLoaiTimKiem = new javax.swing.JLabel();
        Muon_txtTheLoaiTimKiem = new javax.swing.JTextField();
        Muon_lbMaSachTimKiem = new javax.swing.JLabel();
        Muon_txtMaSachTimKiem = new javax.swing.JTextField();
        Muon_btTimKiemSach = new javax.swing.JButton();
        Muon_cbTimTheo = new javax.swing.JComboBox<>();
        Muon_lbTenSachTimKiem = new javax.swing.JLabel();
        Muon_txtTenSachTimKiem = new javax.swing.JTextField();
        Muon_lbSach = new javax.swing.JLabel();
        TraSach = new javax.swing.JPanel();
        TraSach_lbSLTra = new javax.swing.JLabel();
        TraSach_txtSLTra = new javax.swing.JTextField();
        TraSach_bt = new javax.swing.JButton();
        TraSach_lbMaKH = new javax.swing.JLabel();
        TraSach_txtMaKH = new javax.swing.JTextField();
        TraSach_lbTenKH = new javax.swing.JLabel();
        TraSach_txtTenKH = new javax.swing.JTextField();
        TraSach_txtTenSach = new javax.swing.JTextField();
        TraSach_lbTenSach = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TraSach_tbDSTra = new javax.swing.JTable();
        TraSach_lbDSTra = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TraSach_tbDSMuon = new javax.swing.JTable();
        TraSach_lbMaSach = new javax.swing.JLabel();
        TraSach_txtMaSachTimKiem = new javax.swing.JTextField();
        TraSach_btTimKiemSach = new javax.swing.JButton();
        TraSach_cbTimTheo = new javax.swing.JComboBox<>();
        Muon_lbTenSachTimKiem1 = new javax.swing.JLabel();
        TraSach_txtTenSachTimKiem = new javax.swing.JTextField();
        TraSach_lbDSMuon = new javax.swing.JLabel();
        TraSach_lbTheLoai = new javax.swing.JLabel();
        TraSach_txtTheLoaiTimKiem = new javax.swing.JTextField();
        TraSach_lbNgayMuon = new javax.swing.JLabel();
        TraSach_txtNgayMuon = new javax.swing.JTextField();
        TruyVan = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TruyVan_tbDonMuon = new javax.swing.JTable();
        TruyVan_bt = new javax.swing.JButton();
        TruyVan_txtNamMuon = new javax.swing.JTextField();
        TruyVan_txtNgayMuon = new javax.swing.JTextField();
        TruyVan_txtThangMuon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        TruyVan_txtNgayTra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TruyVan_txtThangTra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TruyVan_txtNamTra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TruyVan_lbQuaHan = new javax.swing.JButton();
        TruyVan_lbLayTT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        TimKiem.setLayout(null);

        TimKiem_tbDSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên Khách hàng", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TimKiem_tbDSKH);

        TimKiem.add(jScrollPane3);
        jScrollPane3.setBounds(40, 290, 770, 350);

        TimKiem_cbGet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_cbGet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã", "Tên Bạn đọc", "Số Điện thoại" }));
        TimKiem_cbGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiem_cbGetActionPerformed(evt);
            }
        });
        TimKiem.add(TimKiem_cbGet);
        TimKiem_cbGet.setBounds(580, 30, 120, 30);

        TimKiem_btTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_btTim.setText("Tìm Kiếm");
        TimKiem_btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiem_btTimActionPerformed(evt);
            }
        });
        TimKiem.add(TimKiem_btTim);
        TimKiem_btTim.setBounds(580, 110, 110, 40);

        TimKiem_btMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_btMuon.setText("Mượn sách");
        TimKiem_btMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiem_btMuonActionPerformed(evt);
            }
        });
        TimKiem.add(TimKiem_btMuon);
        TimKiem_btMuon.setBounds(630, 210, 130, 50);

        TimKiem_lbSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_lbSDT.setText("Số điện thoại:");
        TimKiem.add(TimKiem_lbSDT);
        TimKiem_lbSDT.setBounds(90, 110, 110, 30);

        TimKiem_lbMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_lbMaKH.setText("Mã:");
        TimKiem.add(TimKiem_lbMaKH);
        TimKiem_lbMaKH.setBounds(90, 30, 110, 30);

        TimKiem_lbTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_lbTenKH.setText("Tên Bạn đọc:");
        TimKiem.add(TimKiem_lbTenKH);
        TimKiem_lbTenKH.setBounds(90, 70, 110, 30);

        TimKiem_txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_txtSDT.setEnabled(false);
        TimKiem_txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiem_txtSDTActionPerformed(evt);
            }
        });
        TimKiem.add(TimKiem_txtSDT);
        TimKiem_txtSDT.setBounds(220, 110, 210, 26);

        TimKiem_txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiem_txtMaKHActionPerformed(evt);
            }
        });
        TimKiem.add(TimKiem_txtMaKH);
        TimKiem_txtMaKH.setBounds(220, 30, 210, 26);

        TimKiem_txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_txtTenKH.setEnabled(false);
        TimKiem_txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiem_txtTenKHActionPerformed(evt);
            }
        });
        TimKiem.add(TimKiem_txtTenKH);
        TimKiem_txtTenKH.setBounds(220, 70, 210, 26);

        TimKiem_lbTimTheo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem_lbTimTheo.setText("Tìm theo:");
        TimKiem.add(TimKiem_lbTimTheo);
        TimKiem_lbTimTheo.setBounds(500, 40, 60, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tìm Kiếm", jPanel1);

        Muon.setLayout(null);

        Muon_tbDSMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên sách", "Số lượng mượn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Muon_tbDSMuon.setEnabled(false);
        jScrollPane1.setViewportView(Muon_tbDSMuon);

        Muon.add(jScrollPane1);
        jScrollPane1.setBounds(40, 300, 410, 340);

        Muon_tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Muon_tbSach.setEnabled(false);
        jScrollPane2.setViewportView(Muon_tbSach);

        Muon.add(jScrollPane2);
        jScrollPane2.setBounds(590, 300, 430, 350);

        Muon_lbSLMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbSLMuon.setText("Số lượng mượn:");
        Muon.add(Muon_lbSLMuon);
        Muon_lbSLMuon.setBounds(60, 170, 120, 30);

        Muon_txtSLMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtSLMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtSLMuonActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtSLMuon);
        Muon_txtSLMuon.setBounds(180, 170, 221, 26);

        Muon_bt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_bt.setText("Mượn");
        Muon_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_btActionPerformed(evt);
            }
        });
        Muon.add(Muon_bt);
        Muon_bt.setBounds(430, 130, 90, 27);

        Muon_lbMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbMaKH.setText("Mã bạn đọc:");
        Muon.add(Muon_lbMaKH);
        Muon_lbMaKH.setBounds(60, 50, 120, 30);

        Muon_txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtMaKH.setEnabled(false);
        Muon_txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtMaKHActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtMaKH);
        Muon_txtMaKH.setBounds(180, 50, 221, 26);

        Muon_lbTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbTenKH.setText("Tên bạn đọc: ");
        Muon.add(Muon_lbTenKH);
        Muon_lbTenKH.setBounds(60, 90, 120, 30);

        Muon_txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtTenKH.setEnabled(false);
        Muon_txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtTenKHActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtTenKH);
        Muon_txtTenKH.setBounds(180, 90, 221, 26);

        Muon_txtTenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtTenSach.setEnabled(false);
        Muon_txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtTenSachActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtTenSach);
        Muon_txtTenSach.setBounds(180, 130, 221, 26);

        Muon_lbTenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbTenSach.setText("Tên sách:");
        Muon.add(Muon_lbTenSach);
        Muon_lbTenSach.setBounds(60, 130, 120, 30);

        Muon_btTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_btTim.setText("Tìm kiếm");
        Muon_btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_btTimActionPerformed(evt);
            }
        });
        Muon.add(Muon_btTim);
        Muon_btTim.setBounds(430, 50, 90, 27);

        Muon_lbDSMuon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Muon_lbDSMuon.setText("Danh sách Mượn");
        Muon.add(Muon_lbDSMuon);
        Muon_lbDSMuon.setBounds(40, 250, 140, 30);

        Muon_lbTheLoaiTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbTheLoaiTimKiem.setText("Thể loại:");
        Muon.add(Muon_lbTheLoaiTimKiem);
        Muon_lbTheLoaiTimKiem.setBounds(630, 120, 70, 30);

        Muon_txtTheLoaiTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtTheLoaiTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtTheLoaiTimKiemActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtTheLoaiTimKiem);
        Muon_txtTheLoaiTimKiem.setBounds(710, 120, 180, 26);

        Muon_lbMaSachTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbMaSachTimKiem.setText("Mã sách:");
        Muon.add(Muon_lbMaSachTimKiem);
        Muon_lbMaSachTimKiem.setBounds(630, 40, 70, 30);

        Muon_txtMaSachTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtMaSachTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtMaSachTimKiemActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtMaSachTimKiem);
        Muon_txtMaSachTimKiem.setBounds(710, 40, 180, 26);

        Muon_btTimKiemSach.setText("Tìm Kiếm Sách");
        Muon.add(Muon_btTimKiemSach);
        Muon_btTimKiemSach.setBounds(740, 170, 110, 30);

        Muon_cbTimTheo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_cbTimTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Sách", "Tên Sách", "Thể Loại" }));
        Muon.add(Muon_cbTimTheo);
        Muon_cbTimTheo.setBounds(940, 80, 90, 22);

        Muon_lbTenSachTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbTenSachTimKiem.setText("Tên sách:");
        Muon.add(Muon_lbTenSachTimKiem);
        Muon_lbTenSachTimKiem.setBounds(630, 80, 70, 30);

        Muon_txtTenSachTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_txtTenSachTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muon_txtTenSachTimKiemActionPerformed(evt);
            }
        });
        Muon.add(Muon_txtTenSachTimKiem);
        Muon_txtTenSachTimKiem.setBounds(710, 80, 180, 26);

        Muon_lbSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Muon_lbSach.setText("Kho Sách");
        Muon.add(Muon_lbSach);
        Muon_lbSach.setBounds(590, 250, 90, 25);

        jTabbedPane1.addTab("Mượn sách", Muon);

        TraSach.setLayout(null);

        TraSach_lbSLTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_lbSLTra.setText("Số lượng trả:");
        TraSach.add(TraSach_lbSLTra);
        TraSach_lbSLTra.setBounds(60, 170, 120, 30);

        TraSach_txtSLTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_txtSLTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_txtSLTraActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_txtSLTra);
        TraSach_txtSLTra.setBounds(180, 170, 221, 26);

        TraSach_bt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_bt.setText("Trả");
        TraSach_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_btActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_bt);
        TraSach_bt.setBounds(430, 130, 80, 27);

        TraSach_lbMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_lbMaKH.setText("Mã bạn đọc:");
        TraSach.add(TraSach_lbMaKH);
        TraSach_lbMaKH.setBounds(60, 50, 120, 30);

        TraSach_txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_txtMaKH.setEnabled(false);
        TraSach_txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_txtMaKHActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_txtMaKH);
        TraSach_txtMaKH.setBounds(180, 50, 221, 26);

        TraSach_lbTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_lbTenKH.setText("Tên bạn đọc: ");
        TraSach.add(TraSach_lbTenKH);
        TraSach_lbTenKH.setBounds(60, 90, 120, 30);

        TraSach_txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_txtTenKH.setEnabled(false);
        TraSach_txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_txtTenKHActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_txtTenKH);
        TraSach_txtTenKH.setBounds(180, 90, 221, 26);

        TraSach_txtTenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_txtTenSach.setEnabled(false);
        TraSach_txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_txtTenSachActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_txtTenSach);
        TraSach_txtTenSach.setBounds(180, 130, 221, 26);

        TraSach_lbTenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_lbTenSach.setText("Tên sách:");
        TraSach.add(TraSach_lbTenSach);
        TraSach_lbTenSach.setBounds(60, 130, 120, 30);

        TraSach_tbDSTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên sách", "Số lượng trả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TraSach_tbDSTra.setEnabled(false);
        jScrollPane4.setViewportView(TraSach_tbDSTra);

        TraSach.add(jScrollPane4);
        jScrollPane4.setBounds(40, 300, 410, 340);

        TraSach_lbDSTra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TraSach_lbDSTra.setText("Danh sách Trả");
        TraSach.add(TraSach_lbDSTra);
        TraSach_lbDSTra.setBounds(40, 250, 140, 30);

        TraSach_tbDSMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Số lượng", "Ngày mượn", "Ngày trả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TraSach_tbDSMuon.setEnabled(false);
        jScrollPane5.setViewportView(TraSach_tbDSMuon);

        TraSach.add(jScrollPane5);
        jScrollPane5.setBounds(640, 290, 560, 350);

        TraSach_lbMaSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_lbMaSach.setText("Mã sách:");
        TraSach.add(TraSach_lbMaSach);
        TraSach_lbMaSach.setBounds(790, 30, 70, 30);

        TraSach_txtMaSachTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_txtMaSachTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_txtMaSachTimKiemActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_txtMaSachTimKiem);
        TraSach_txtMaSachTimKiem.setBounds(880, 30, 180, 26);

        TraSach_btTimKiemSach.setText("Tìm Kiếm");
        TraSach_btTimKiemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_btTimKiemSachActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_btTimKiemSach);
        TraSach_btTimKiemSach.setBounds(910, 210, 90, 30);

        TraSach_cbTimTheo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_cbTimTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Sách", "Tên Sách", "Thể Loại", "Ngày mượn" }));
        TraSach.add(TraSach_cbTimTheo);
        TraSach_cbTimTheo.setBounds(1100, 70, 90, 22);

        Muon_lbTenSachTimKiem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Muon_lbTenSachTimKiem1.setText("Tên sách:");
        TraSach.add(Muon_lbTenSachTimKiem1);
        Muon_lbTenSachTimKiem1.setBounds(790, 70, 70, 30);

        TraSach_txtTenSachTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_txtTenSachTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_txtTenSachTimKiemActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_txtTenSachTimKiem);
        TraSach_txtTenSachTimKiem.setBounds(880, 70, 180, 26);

        TraSach_lbDSMuon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TraSach_lbDSMuon.setText("Danh sách đang mượn");
        TraSach.add(TraSach_lbDSMuon);
        TraSach_lbDSMuon.setBounds(640, 250, 190, 25);

        TraSach_lbTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_lbTheLoai.setText("Thể loại:");
        TraSach.add(TraSach_lbTheLoai);
        TraSach_lbTheLoai.setBounds(790, 110, 70, 30);

        TraSach_txtTheLoaiTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_txtTheLoaiTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_txtTheLoaiTimKiemActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_txtTheLoaiTimKiem);
        TraSach_txtTheLoaiTimKiem.setBounds(880, 110, 180, 26);

        TraSach_lbNgayMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_lbNgayMuon.setText("Ngày mượn:");
        TraSach.add(TraSach_lbNgayMuon);
        TraSach_lbNgayMuon.setBounds(790, 150, 80, 30);

        TraSach_txtNgayMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraSach_txtNgayMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraSach_txtNgayMuonActionPerformed(evt);
            }
        });
        TraSach.add(TraSach_txtNgayMuon);
        TraSach_txtNgayMuon.setBounds(880, 150, 180, 26);

        jTabbedPane1.addTab("Trả Sách", TraSach);

        TruyVan.setLayout(null);

        TruyVan_tbDonMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã mượn", "Tên khách hàng", "Tên sách", "Số lượng mượn", "Ngày mượn", "Ngày trả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TruyVan_tbDonMuon);

        TruyVan.add(jScrollPane6);
        jScrollPane6.setBounds(80, 170, 880, 500);

        TruyVan_bt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TruyVan_bt.setText("Truy vấn");
        TruyVan_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_btActionPerformed(evt);
            }
        });
        TruyVan.add(TruyVan_bt);
        TruyVan_bt.setBounds(780, 40, 210, 80);

        TruyVan_txtNamMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtNamMuonActionPerformed(evt);
            }
        });
        TruyVan.add(TruyVan_txtNamMuon);
        TruyVan_txtNamMuon.setBounds(380, 110, 70, 30);

        TruyVan_txtNgayMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtNgayMuonActionPerformed(evt);
            }
        });
        TruyVan.add(TruyVan_txtNgayMuon);
        TruyVan_txtNgayMuon.setBounds(220, 110, 50, 30);

        TruyVan_txtThangMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtThangMuonActionPerformed(evt);
            }
        });
        TruyVan.add(TruyVan_txtThangMuon);
        TruyVan_txtThangMuon.setBounds(300, 110, 50, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("/");
        TruyVan.add(jLabel1);
        jLabel1.setBounds(360, 100, 14, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("/");
        TruyVan.add(jLabel2);
        jLabel2.setBounds(280, 100, 14, 40);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        TruyVan.add(jTextField5);
        jTextField5.setBounds(220, 110, 50, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("/");
        TruyVan.add(jLabel3);
        jLabel3.setBounds(280, 100, 14, 40);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        TruyVan.add(jTextField6);
        jTextField6.setBounds(300, 110, 50, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("/");
        TruyVan.add(jLabel4);
        jLabel4.setBounds(360, 100, 14, 40);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        TruyVan.add(jTextField7);
        jTextField7.setBounds(380, 110, 70, 30);

        TruyVan_txtNgayTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtNgayTraActionPerformed(evt);
            }
        });
        TruyVan.add(TruyVan_txtNgayTra);
        TruyVan_txtNgayTra.setBounds(540, 110, 50, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("/");
        TruyVan.add(jLabel5);
        jLabel5.setBounds(600, 100, 14, 40);

        TruyVan_txtThangTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtThangTraActionPerformed(evt);
            }
        });
        TruyVan.add(TruyVan_txtThangTra);
        TruyVan_txtThangTra.setBounds(620, 110, 50, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setText("/");
        TruyVan.add(jLabel6);
        jLabel6.setBounds(680, 100, 14, 40);

        TruyVan_txtNamTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_txtNamTraActionPerformed(evt);
            }
        });
        TruyVan.add(TruyVan_txtNamTra);
        TruyVan_txtNamTra.setBounds(700, 110, 70, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("đến");
        TruyVan.add(jLabel7);
        jLabel7.setBounds(470, 100, 90, 48);

        TruyVan_lbQuaHan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TruyVan_lbQuaHan.setText("Quá hạn Trả");
        TruyVan_lbQuaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruyVan_lbQuaHanActionPerformed(evt);
            }
        });
        TruyVan.add(TruyVan_lbQuaHan);
        TruyVan_lbQuaHan.setBounds(130, 40, 180, 40);

        TruyVan_lbLayTT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TruyVan_lbLayTT.setText("Lấy thông tin");
        TruyVan.add(TruyVan_lbLayTT);
        TruyVan_lbLayTT.setBounds(360, 40, 190, 40);

        jTabbedPane1.addTab("Truy vấn đơn mượn", TruyVan);

        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Sửa thông tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(530, 80, 120, 30);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(220, 30, 190, 30);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(220, 80, 190, 30);

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField8.setEnabled(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8);
        jTextField8.setBounds(220, 130, 190, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã bạn đọc", "Tên bạn đọc", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable1);

        jPanel2.add(jScrollPane7);
        jScrollPane7.setBounds(100, 250, 890, 380);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Số điện thoại:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 130, 100, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mã:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, 30, 100, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tên bạn đọc:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 80, 100, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Xóa bạn đọc");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(530, 130, 120, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Thêm bạn đọc");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(530, 30, 120, 30);

        jTabbedPane1.addTab("Khách Hàng", jPanel2);

        jLabel11.setText("jLabel11");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel11)
                .addGap(47, 47, 47)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(809, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(627, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin tài khoản", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Muon_txtSLMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtSLMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtSLMuonActionPerformed

    private void Muon_txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtMaKHActionPerformed

    private void Muon_txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtTenKHActionPerformed

    private void Muon_txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtTenSachActionPerformed

    private void Muon_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_btActionPerformed
        try {                                        
            // TODO add your handling code here:
            if(Muon_txtTenKH.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng tìm khách hàng trước!");
                return;
            }
            
            String maKH = Muon_txtMaKH.getText().trim();
            String maSach = Muon_txtTenSach.getText().trim();
            String slMuon = Muon_txtSLMuon.getText().trim();
            
            if(maSach.isEmpty() || slMuon.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách và số lượng!");
                return;
            }
            
            int soluongMuon = 0;
            try {
                soluongMuon = Integer.parseInt(slMuon);
                if(soluongMuon <= 0) throw new Exception();
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Số lượng mượn không hợp lệ!");
                return;
            }
            
            // Kiểm tra sách tồn tại
            Sach sach = sachService.GetSachByMa(maSach);
            if(sach == null) {
                JOptionPane.showMessageDialog(this, "Sách này không tồn tại!");
                return;
            }
            
            // Tạo đối tượng Mượn
            String NgayTra;
            String NgayMuon = LocalDate.now().toString();
            if(LocalDate.now().getDayOfMonth() + 3 > 12) {
                NgayTra = LocalDate.now().plusMonths(LocalDate.now().getDayOfMonth() + 3 - 12).toString();
            }else{
                NgayTra = LocalDate.now().plusMonths(3).toString();
            }

            Muon muon = new Muon(" ",maKH , maSach, soluongMuon, NgayMuon, NgayTra);

            boolean result = managerController.MuonSach(muon, usernameLogin);
            
            if(result) {
                JOptionPane.showMessageDialog(this, "Mượn sách thành công!");
                loadTableSachDaMuon(maKH);
                loadTableKhoSach();
            }
            else {
                JOptionPane.showMessageDialog(this, "Mượn sách thất bại!");
            }
            
        } catch(IOException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null,ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Muon_btActionPerformed

    private void loadTableSachDaMuon(String maKH) {
        DefaultTableModel model = (DefaultTableModel) Muon_tbDSMuon.getModel();
        model.setRowCount(0);
        
        ArrayList<Muon> list = managerController.GetMuonByMa(maKH);
        
        if(list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sách đã mượn!");
            return;
        }
        
        for(Muon m : list) {
            model.addRow(new Object[]
            {
                m.getMaMuon(),
                m.getMaSach(),
                m.getSoLuong(),
                m.getNgayMuon()
            }); 
        }
    }
    
    // Clear dữ liệu Bảng nếu KH không tồn tại
    private void clearTableMuon() {
        DefaultTableModel model = (DefaultTableModel) Muon_tbDSMuon.getModel();
        model.setRowCount(0);
    }
    
    private void loadTableKhoSach()  {
        try {
            DefaultTableModel model = (DefaultTableModel) Muon_tbSach.getModel();
            model.setRowCount(0);
            
            ArrayList<Sach> list = sachService.GetAllSach();
            
            for(Sach s : list) {
                model.addRow(new Object[] {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getSoLuong()
                });
            }
        } catch (IOException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Muon_btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_btTimActionPerformed
        // TODO add your handling code here:
        String maKH = Muon_txtMaKH.getText().trim();
        
        if(maKH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng!");
            return;
        }
        
        KhachHang khachHang = managerController.GetKhachHangByMa(maKH);
        
        if(khachHang == null) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy người dùng này!!!");
            Muon_txtTenKH.setText("");
            clearTableMuon();
            return;
        }
        // Hiển thị tên khách hàng
        Muon_txtTenKH.setText(khachHang.getTenKH());
        Muon_txtTenKH.setEditable(false);
        
        // Load dữ liệu
        loadTableSachDaMuon(maKH);
        loadTableKhoSach();
    }//GEN-LAST:event_Muon_btTimActionPerformed

    private void TimKiem_btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiem_btTimActionPerformed
        // TODO add your handling code here:
        int index = TimKiem_cbGet.getSelectedIndex();
        
        DefaultTableModel model = (DefaultTableModel) TimKiem_tbDSKH.getModel();
        model.setRowCount(0);
        
        // Tìm theo Mã khách hàng
        if(index == 0) {
            
        }
    }//GEN-LAST:event_TimKiem_btTimActionPerformed

    private void TimKiem_cbGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiem_cbGetActionPerformed
        // TODO add your handling code here:
        
        int index = TimKiem_cbGet.getSelectedIndex();
        TimKiem_cbGet.setSelectedIndex(index);
        
        // Reset text
        TimKiem_txtMaKH.setText("");
        TimKiem_txtTenKH.setText("");
        TimKiem_txtSDT.setText("");
        
        switch (index) {
            case 0 -> {
                TimKiem_txtMaKH.setEnabled(true);
                TimKiem_txtTenKH.setEnabled(false);
                TimKiem_txtSDT.setEnabled(false);
            }
            case 1 -> {
                TimKiem_txtMaKH.setEnabled(false);
                TimKiem_txtTenKH.setEnabled(true);
                TimKiem_txtSDT.setEnabled(false);
            }
            case 2 -> {
                TimKiem_txtMaKH.setEnabled(false);
                TimKiem_txtTenKH.setEnabled(false);
                TimKiem_txtSDT.setEnabled(true);
            }
            default -> {
            }
        }
    }//GEN-LAST:event_TimKiem_cbGetActionPerformed

    private void loadTableKH(ArrayList<KhachHang> list) {
        DefaultTableModel model = (DefaultTableModel) TimKiem_tbDSKH.getModel();
        model.setRowCount(0);
        
        for(KhachHang kh : list) {
            model.addRow(new Object[] {
                kh.getMaKH(),
                kh.getTenKH(),
                kh.getSdtKH()
            });
        }
    }
    
    private void TimKiem_btMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiem_btMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiem_btMuonActionPerformed

    private void TimKiem_txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiem_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiem_txtSDTActionPerformed

    private void TimKiem_txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiem_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiem_txtMaKHActionPerformed

    private void TimKiem_txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiem_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiem_txtTenKHActionPerformed

    private void Muon_txtTheLoaiTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtTheLoaiTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtTheLoaiTimKiemActionPerformed

    private void Muon_txtMaSachTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtMaSachTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtMaSachTimKiemActionPerformed

    private void Muon_txtTenSachTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muon_txtTenSachTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Muon_txtTenSachTimKiemActionPerformed

    private void TraSach_txtSLTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_txtSLTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_txtSLTraActionPerformed

    private void TraSach_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_btActionPerformed

    private void TraSach_txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_txtMaKHActionPerformed

    private void TraSach_txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_txtTenKHActionPerformed

    private void TraSach_txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_txtTenSachActionPerformed

    private void TraSach_txtMaSachTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_txtMaSachTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_txtMaSachTimKiemActionPerformed

    private void TraSach_txtTenSachTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_txtTenSachTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_txtTenSachTimKiemActionPerformed

    private void TraSach_txtTheLoaiTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_txtTheLoaiTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_txtTheLoaiTimKiemActionPerformed

    private void TraSach_txtNgayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_txtNgayMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_txtNgayMuonActionPerformed

    private void TraSach_btTimKiemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraSach_btTimKiemSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraSach_btTimKiemSachActionPerformed

    private void TruyVan_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_btActionPerformed

    private void TruyVan_txtNamMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtNamMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtNamMuonActionPerformed

    private void TruyVan_txtNgayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtNgayMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtNgayMuonActionPerformed

    private void TruyVan_txtThangMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtThangMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtThangMuonActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void TruyVan_txtNgayTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtNgayTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtNgayTraActionPerformed

    private void TruyVan_txtThangTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtThangTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtThangTraActionPerformed

    private void TruyVan_txtNamTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_txtNamTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_txtNamTraActionPerformed

    private void TruyVan_lbQuaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruyVan_lbQuaHanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruyVan_lbQuaHanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Muon;
    private javax.swing.JButton Muon_bt;
    private javax.swing.JButton Muon_btTim;
    private javax.swing.JButton Muon_btTimKiemSach;
    private javax.swing.JComboBox<String> Muon_cbTimTheo;
    private javax.swing.JLabel Muon_lbDSMuon;
    private javax.swing.JLabel Muon_lbMaKH;
    private javax.swing.JLabel Muon_lbMaSachTimKiem;
    private javax.swing.JLabel Muon_lbSLMuon;
    private javax.swing.JLabel Muon_lbSach;
    private javax.swing.JLabel Muon_lbTenKH;
    private javax.swing.JLabel Muon_lbTenSach;
    private javax.swing.JLabel Muon_lbTenSachTimKiem;
    private javax.swing.JLabel Muon_lbTenSachTimKiem1;
    private javax.swing.JLabel Muon_lbTheLoaiTimKiem;
    private javax.swing.JTable Muon_tbDSMuon;
    private javax.swing.JTable Muon_tbSach;
    private javax.swing.JTextField Muon_txtMaKH;
    private javax.swing.JTextField Muon_txtMaSachTimKiem;
    private javax.swing.JTextField Muon_txtSLMuon;
    private javax.swing.JTextField Muon_txtTenKH;
    private javax.swing.JTextField Muon_txtTenSach;
    private javax.swing.JTextField Muon_txtTenSachTimKiem;
    private javax.swing.JTextField Muon_txtTheLoaiTimKiem;
    private javax.swing.JPanel TimKiem;
    private javax.swing.JButton TimKiem_btMuon;
    private javax.swing.JButton TimKiem_btTim;
    private javax.swing.JComboBox<String> TimKiem_cbGet;
    private javax.swing.JLabel TimKiem_lbMaKH;
    private javax.swing.JLabel TimKiem_lbSDT;
    private javax.swing.JLabel TimKiem_lbTenKH;
    private javax.swing.JLabel TimKiem_lbTimTheo;
    private javax.swing.JTable TimKiem_tbDSKH;
    private javax.swing.JTextField TimKiem_txtMaKH;
    private javax.swing.JTextField TimKiem_txtSDT;
    private javax.swing.JTextField TimKiem_txtTenKH;
    private javax.swing.JPanel TraSach;
    private javax.swing.JButton TraSach_bt;
    private javax.swing.JButton TraSach_btTimKiemSach;
    private javax.swing.JComboBox<String> TraSach_cbTimTheo;
    private javax.swing.JLabel TraSach_lbDSMuon;
    private javax.swing.JLabel TraSach_lbDSTra;
    private javax.swing.JLabel TraSach_lbMaKH;
    private javax.swing.JLabel TraSach_lbMaSach;
    private javax.swing.JLabel TraSach_lbNgayMuon;
    private javax.swing.JLabel TraSach_lbSLTra;
    private javax.swing.JLabel TraSach_lbTenKH;
    private javax.swing.JLabel TraSach_lbTenSach;
    private javax.swing.JLabel TraSach_lbTheLoai;
    private javax.swing.JTable TraSach_tbDSMuon;
    private javax.swing.JTable TraSach_tbDSTra;
    private javax.swing.JTextField TraSach_txtMaKH;
    private javax.swing.JTextField TraSach_txtMaSachTimKiem;
    private javax.swing.JTextField TraSach_txtNgayMuon;
    private javax.swing.JTextField TraSach_txtSLTra;
    private javax.swing.JTextField TraSach_txtTenKH;
    private javax.swing.JTextField TraSach_txtTenSach;
    private javax.swing.JTextField TraSach_txtTenSachTimKiem;
    private javax.swing.JTextField TraSach_txtTheLoaiTimKiem;
    private javax.swing.JPanel TruyVan;
    private javax.swing.JButton TruyVan_bt;
    private javax.swing.JButton TruyVan_lbLayTT;
    private javax.swing.JButton TruyVan_lbQuaHan;
    private javax.swing.JTable TruyVan_tbDonMuon;
    private javax.swing.JTextField TruyVan_txtNamMuon;
    private javax.swing.JTextField TruyVan_txtNamTra;
    private javax.swing.JTextField TruyVan_txtNgayMuon;
    private javax.swing.JTextField TruyVan_txtNgayTra;
    private javax.swing.JTextField TruyVan_txtThangMuon;
    private javax.swing.JTextField TruyVan_txtThangTra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
