//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLYTHuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiSuGiaoDich
    {
        public string MaGD { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> NgayGD { get; set; }
        public string MaSach { get; set; }
        public string SoLuong { get; set; }
        public string TrangThai { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
