//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLYTHuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string Username { get; set; }
        public string Pass { get; set; }
        public string TenTK { get; set; }
        public string SdtTK { get; set; }
        public string Role { get; set; }
    }
}
